### ISSUE TITLE
null pointer exception at org.jcrom.util.JcrUtils.createValue

### ISSUE THREAD

**Issue by Kobee1203** [Kobee1203/jcrom#114]
Reported by rgummalla (https://code.google.com/u/117290624658331484966/), May 29, 2015
I am getting the below exception while using 2.1.0 version while making calls to jackrabbit oak 1.0.13

java.lang.NullPointerException: null
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:192)
at org.apache.jackrabbit.oak.plugins.memory.StringPropertyState.<init>(StringPropertyState.java:36)
at org.apache.jackrabbit.oak.plugins.memory.StringPropertyState.stringProperty(StringPropertyState.java:47)
at org.apache.jackrabbit.oak.plugins.value.ValueFactoryImpl.createValue(ValueFactoryImpl.java:138)
at org.jcrom.util.JcrUtils.createValue(JcrUtils.java:191)
at org.jcrom.PropertyMapper.mapToProperty(PropertyMapper.java:356)
at org.jcrom.PropertyMapper.mapFieldToProperty(PropertyMapper.java:285)
at org.jcrom.PropertyMapper.addProperty(PropertyMapper.java:291)
at org.jcrom.Mapper.addNode(Mapper.java:495)
at org.jcrom.Mapper.addNode(Mapper.java:447)
at org.jcrom.ChildNodeMapper.addSingleChildToNode(ChildNodeMapper.java:117)
at org.jcrom.ChildNodeMapper.setChildren(ChildNodeMapper.java:258)
at org.jcrom.ChildNodeMapper.addChildren(ChildNodeMapper.java:265)
at org.jcrom.Mapper.addNode(Mapper.java:501)
at org.jcrom.Mapper.addNode(Mapper.java:447)
at org.jcrom.ChildNodeMapper.addSingleChildToNode(ChildNodeMapper.java:117)
at org.jcrom.ChildNodeMapper.setChildren(ChildNodeMapper.java:258)
at org.jcrom.ChildNodeMapper.addChildren(ChildNodeMapper.java:265)
at org.jcrom.Mapper.addNode(Mapper.java:501)
at org.jcrom.Mapper.addNode(Mapper.java:447)
at org.jcrom.ChildNodeMapper.addSingleChildToNode(ChildNodeMapper.java:117)
at org.jcrom.ChildNodeMapper.setChildren(ChildNodeMapper.java:258)
at org.jcrom.ChildNodeMapper.addChildren(ChildNodeMapper.java:265)
at org.jcrom.Mapper.addNode(Mapper.java:501)
at org.jcrom.Mapper.addNode(Mapper.java:447)
at org.jcrom.Jcrom.addNode(Jcrom.java:348)
at org.jcrom.dao.AbstractJcrDAO.create(AbstractJcrDAO.java:260)
at org.jcrom.dao.AbstractJcrDAO.create(AbstractJcrDAO.java:239)
at com.sapient.cms.dao.jcrom.GenericJcrDaoImpl.addOrUpdate(GenericJcrDaoImpl.java:76)
at com.mgm.content.sync.services.osgi.impl.CCMServiceImpl.addOrUpdateProgram(CCMServiceImpl.java:627)
at com.mgm.content.sync.services.osgi.impl.CCMServiceImpl.write(CCMServiceImpl.java:238)
at com.mgm.content.sync.services.jms.listener.PhoenixMessageListener.onMessage(PhoenixMessageListener.java:96)
at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:562)
at com.mgm.content.sync.services.jms.impl.CustomMessageListenerContainer.doInvokeListener(CustomMessageListenerContainer.java:48)
at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:500)
at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:468)
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:325)
at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:263)
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1103)
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1095)
at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:992)
at java.lang.Thread.run(Thread.java:745)

**Comment by Kobee1203** [comment]
Cannot reproduce.
